[package]
name = "cube-parse"
version = "0.2.0"
authors = ["HarkonenBade<github@harkonen.net>", "Danilo Bargen <mail@dbrgn.ch>"]
edition = "2018"

[dependencies]
clap = "2"
serde = "1.0"
serde-xml-rs = "0.2"
serde_derive = "1.0"
regex = "1.1"
lazy_static = "1.2"
alphanumeric-sort = "1.0"
